# This file defines a GitHub Action for uploading and publishing Chrome extensions to the Chrome Web Store using the API.
# It specifies required and optional inputs, Docker-based execution, and branding for the action.
# The action supports both ZIP and CRX uploads, OAuth2 authentication, and optional expedited review.
#
# Inputs section lists all parameters needed for the action, including extension details and authentication.
# The 'runs' section configures the Docker image and entrypoint for execution.
# Branding section customizes the action's appearance in the GitHub Actions UI.
#
# To use the action, you need to create a Google Cloud project and enable the Chrome Web Store API.
# Documentation of that can be found here: https://developer.chrome.com/docs/webstore/using-api.
name: 'Chrome Webstore Publish'
description: 'Upload and publish Chrome extension ZIPs or CRX to the Chrome Web Store via API.'
author: 'Puzzlers Labs'

inputs:
  # Mode of operation: sign or publish. Default is publish (for backward compatibility)
  mode:
    description: 'Mode of operation: sign or publish. (Default: publish)'
    required: true
    default: 'publish'

  # The unique ID of the Chrome extension to update or publish.
  # It is a 32 character hexadecimal string.
  extension_id:
    description: 'Chrome Web Store extension ID.'
    required: true

  # Path to the ZIP file of the extension to upload.
  zip_file_path:
    description: 'Path to the extension ZIP file.'
    required: true

  # OAuth2 client ID for Google Cloud authentication
  client_id:
    description: 'Google Cloud OAuth2 client ID.'
    required: true

  # OAuth2 client secret for Google Cloud authentication
  client_secret:
    description: 'Google Cloud OAuth2 Client Secret.'
    required: true

  # OAuth2 refresh token for Google Cloud authentication
  refresh_token:
    description: 'Google Cloud OAuth2 Refresh Token.'
    required: true

  # Target audience for publishing: public or testers. Default is public (for common usability)
  publish_target:
    description: 'Publish target: public or testers. (Default: public)'
    required: false
    default: 'public'

  # Whether to request expedited review if eligible
  expedited_review:
    description: 'Request expedited review if eligible (true/false). Falls back to regular review if not eligible.'
    required: false
    default: 'false'

  # Private key data for CRX signing (optional)
  crx_private_key:
    description: 'CRX signing private key (PEM string). If provided, the extension will be signed and uploaded as CRX.'
    required: false

  # Path to the private key file for CRX signing (optional)
  crx_private_key_path:
    description: 'Path to the CRX signing private key (PEM file). If provided, the extension will be signed and uploaded as CRX.'
    required: false

# Specifies Docker as the runtime environment
# and uses the Docker image from GitHub Container Registry (GHCR).
# The entrypoint is set to 'pnpm start' to run the application.
runs:
  using: 'docker'
  image: 'docker://ghcr.io/puzzlers-labs/chrome-webstore-publish:latest'

# Customizes the action's appearance in the GitHub Actions UI.
branding:
  icon: 'upload-cloud'
  color: 'purple'
