name: Update package-download badge

on:
  schedule:
    - cron: '0 0 * * *' # 00:00 UTC daily
  workflow_dispatch: # manual trigger

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch HTML
        run: curl -sL https://github.com/puzzlers-labs/chrome-webstore-publish/pkgs/container/chrome-webstore-publish -o page.html

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install DOM/XPath libs
        run: pnpm install xmldom xpath

      - name: Parse with Node
        id: scraper
        run: |
          value=$(node -e "
            const fs = require('fs');
            const html = fs.readFileSync('page.html', 'utf8');
            const match = html.match(/<span[^>]*>\\s*Total downloads\\s*<\\/span>\\s*<h3[^>]*>(\\d+)<\\/h3>/);
            process.stdout.write(match ? match[1] : '');
          ")
          echo "scraped_value=$value" >> $GITHUB_OUTPUT

      - name: Show result
        run: echo "::notice title=Scraped value::${{ steps.scraper.outputs.scraped_value }}"

    outputs:
      scraped_value: ${{ steps.scraper.outputs.scraped_value }}

  prepare-badge:
    needs: update-badge
    runs-on: ubuntu-latest
    steps:
      - name: Prepare badge JSON
        run: |
          VALUE="${{ needs.update-badge.outputs.scraped_value }}"
          if [ -z "$VALUE" ]; then
            VALUE="Error"
          fi
          cat > action-runs-badge.json <<EOF
          {
            "schemaVersion": 1,
            "label": "Action Runs",
            "message": "$VALUE",
            "color": "blue"
          }
          EOF
      - name: Show badge JSON
        run: cat action-runs-badge.json
