name: Update package-download badge

on:
  schedule:
    - cron: '0 0 * * *' # 00:00 UTC daily
  workflow_dispatch: # manual trigger

env:
  PACKAGE_OWNER: puzzlers-labs # org or user that owns the package
  PACKAGE_NAME: chrome-webstore-publish # package name exactly as shown on GHCR

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch download stats & write JSON (verbose)
        uses: actions/github-script@v7
        env:
          DEBUG: 'true'
        with:
          script: |
            const fs = require('node:fs');          // ✅ still fine

            const query = `
              query ($owner: String!, $pkg: String!) {
                organization(login: $owner) {
                  packages(first: 1, names: [$pkg]) {
                    nodes {
                      name
                      statistics { downloadsTotalCount }
                    }
                  }
                }
              }`;

            const vars = {
              owner: process.env.PACKAGE_OWNER,
              pkg:   process.env.PACKAGE_NAME,
            };

            /* ------------ EXECUTE ------------- */
            const data = await github.graphql(query, vars);

            /* ------------ LOGGING ------------- */
            core.notice('Raw GraphQL response ⬇️');      // core is already in scope
            console.log(JSON.stringify(data, null, 2));
            fs.writeFileSync('raw-stats.json', JSON.stringify(data));

            const downloads =
              data.organization?.packages.nodes[0]?.statistics?.downloadsTotalCount ?? 0;

            core.notice(`downloadsTotalCount → ${downloads}`);

            const badge = {
              schemaVersion: 1,
              label: 'downloads',
              message: downloads.toString(),
              color: downloads ? 'blue' : 'lightgrey',
            };

            fs.writeFileSync(
              'package-downloads-badge.json',
              JSON.stringify(badge, null, 2),
            );

      - name: Commit updated badge
        uses: EndBug/add-and-commit@v9
        with:
          add: 'package-downloads-badge.json'
          author_name: 'puzzlers-tech[bot]'
          author_email: 'tech@puzzlers-labs.com'
          message: 'chore: refresh package download badge'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
