name: GHCR-pull-badge
on:
  workflow_dispatch:
jobs:
  pull-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sum pull counts
        id: pulls
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          IMAGE: chrome-webstore-publish
        run: |
          RESPONSE=$(curl -sL \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$OWNER/$REPO/packages/container/$IMAGE/versions?per_page=100")
          echo "Raw API response: $RESPONSE"
          TOTAL=$(echo "$RESPONSE" | jq '[.[]|.download_count] | add')
          mkdir -p .github
          cat > .github/ghcr-pulls-badge.json <<EOF
          {
            "schemaVersion": 1,
            "label": "ghcr pulls",
            "message": "$TOTAL",
            "color": "blue"
          }
          EOF

      - name: Commit badge
        run: |
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git add .github/ghcr-pulls-badge.json
          git diff --cached --quiet || git commit -m "update GHCR pull badge" && git push
